export interface Contrat {
	date_debut?: string
	statut_conventionnel?: string
	statut_rc?: string
	pcs_ese?: string
	complement_pcs_ese?: string
	libelle_emploi?: string
	nature?: string
	dispositif_politique?: string
	numero?: string
	date_fin_previsionnelle?: string
	unite_mesure?: string
	quotite_categorie?: string
	quotite?: string
	modalite_temps?: string
	complement_base?: string
	ccn?: string
	regime_maladie?: string
	lieu_travail?: string
	regime_vieillesse?: string
	motif_recours?: string
	code_caisse_conges_payes?: string
	taux_fraisprofessionnels?: string
	travailleur_etranger?: string
	motif_exclusion_dsn?: string
	status_emploi?: string
	code_affectation_ac?: string
	numero_interne?: string
	type_gestion_ac?: string
	date_adhesion?: string
	date_denonciation?: string
	date_convention_gestion?: string
	numero_convention_gestion?: string
	code_gestionnaire_risque?: string
	code_emplois_multiples?: string
	code_employeurs_multiples?: string
	code_regime_risque_accident_travail?: string
	code_risque_accident_travail?: string
	positionnement_convention_collective?: string
	code_statut_categoriel_apecita?: string
	taux_accident_travail?: string
	temps_partiel_cotisant_temps_plein?: string
	remuneration_pourboire?: string
	siret_etablissement_utilisateur?: string
	numero_label?: string
	numero_licence_entrepreneur_spectacle?: string
	numero_objet_spectacle?: string
	statut_organisateur_spectacle?: string
	fp_code_complement_pcs_es?: string
	nature_poste?: string
	fp_quotite_travail_temps_complet?: string
	taux_temps_travail_partiel?: string
	code_categorie_service?: string
	fp_indice_brut?: string
	fp_indice_majore?: string
	fpnbi?: string
	fp_indice_brut_origine?: string
	fp_indice_brut_cotisation_emploi_superieur?: string
	fp_ancien_employeur_public?: string
	fp_indice_brut_origine_ancien_salarie_employeur_public?: string
	fp_indice_brut_origine_spp?: string
	fp_maintien_traitement_origine_contractuel_titulaire?: string
	fp_type_detachement?: string
	genre_navigation?: string
	taux_service_actif?: string
	niveau_rx?: string
	echelon?: string
	coefficient_hierarchique?: string
	statut_boeth?: string
	complement_dispositif_politique?: string
	case_mise_disposition_externe?: string
	categorie_classement_finale?: string
	contrat_engagement_maritime?: string
	college_cnieg?: string
	forme_amenagement_temps_partiel?: string
	grade?: string
	cti?: string
	finess_geo?: string
}
