export interface Contrat {
	date_debut?: string
	statut_conventionnel?: string
	statut_rc?: string
	pcs_ese?: string
	complement_pcs_ese?: string
	libelle_emploi?: string
	nature?: string
	dispositif_politique?: string
	numero?: string
	date_fin_previsionnelle?: string
	unite_mesure?: string
	quotite_categorie?: string
	quotite?: string
	modalite_temps?: string
	complement_base?: string
	ccn?: string
	regime_maladie?: string
	lieu_travail?: string
	regime_vieillesse?: string
	motif_recours?: string
	code_caisse_conges_payes?: string
	taux_fraisprofessionnels?: string
	travailleur_etranger?: string
	motif_exclusion_dsn?: string
	status_emploi?: string
	code_affectation_ac?: string
	numero_interne?: string
	type_gestion_ac?: string
	date_adhesion?: string
	date_denonciation?: string
	date_convention_gestion?: string
	numero_convention_gestion?: string
	code_gestionnaire_risque?: string
	code_emplois_multiples?: string
	code_employeurs_multiples?: string
	code_regime_risque_accident_travail?: string
	code_risque_accident_travail?: string
	positionnement_convention_collective?: string
	code_statut_categoriel_apecita?: string
	taux_accident_travail?: string
	temps_partiel_cotisant_temps_plein?: string
	remuneration_pourboire?: string
	siret_etablissement_utilisateur?: string
	numero_label?: string
	numero_licence_entrepreneur_spectacle?: string
	numero_objet_spectacle?: string
	statut_organisateur_spectacle?: string
	fp_code_complement_pcs_es?: string
	nature_poste?: string
	fp_quotite_travail_temps_complet?: string
	taux_temps_travail_partiel?: string
	code_categorie_service?: string
	fp_indice_brut?: string
	fp_indice_majore?: string
	fpnbi?: string
	fp_indice_brut_origine?: string
	fp_indice_brut_cotisation_emploi_superieur?: string
	fp_ancien_employeur_public?: string
	fp_indice_brut_origine_ancien_salarie_employeur_public?: string
	fp_indice_brut_origine_spp?: string
	fp_maintien_traitement_origine_contractuel_titulaire?: string
	fp_type_detachement?: string
	genre_navigation?: string
	taux_service_actif?: string
	niveau_rx?: string
	echelon?: string
	coefficient_hierarchique?: string
	statut_boeth?: string
	complement_dispositif_politique?: string
	case_mise_disposition_externe?: string
	categorie_classement_finale?: string
	contrat_engagement_maritime?: string
	college_cnieg?: string
	forme_amenagement_temps_partiel?: string
	grade?: string
	cti?: string
	finess_geo?: string
}

// DSN block S21.G00.40 - Contrat
export const CONTRAT_FIELDS: Record<string, keyof Contrat> = {
	"001": "date_debut",
	"002": "statut_conventionnel",
	"003": "statut_rc",
	"004": "pcs_ese",
	"005": "complement_pcs_ese",
	"006": "libelle_emploi",
	"007": "nature",
	"008": "dispositif_politique",
	"009": "numero",
	"010": "date_fin_previsionnelle",
	"011": "unite_mesure",
	"012": "quotite_categorie",
	"013": "quotite",
	"014": "modalite_temps",
	"016": "complement_base",
	"017": "ccn",
	"018": "regime_maladie",
	"019": "lieu_travail",
	"020": "regime_vieillesse",
	"021": "motif_recours",
	"022": "code_caisse_conges_payes",
	"023": "taux_fraisprofessionnels",
	"024": "travailleur_etranger",
	"025": "motif_exclusion_dsn",
	"026": "status_emploi",
	"027": "code_affectation_ac",
	"028": "numero_interne",
	"029": "type_gestion_ac",
	"030": "date_adhesion",
	"031": "date_denonciation",
	"032": "date_convention_gestion",
	"033": "numero_convention_gestion",
	"035": "code_gestionnaire_risque",
	"036": "code_emplois_multiples",
	"037": "code_employeurs_multiples",
	"039": "code_regime_risque_accident_travail",
	"040": "code_risque_accident_travail",
	"041": "positionnement_convention_collective",
	"042": "code_statut_categoriel_apecita",
	"043": "taux_accident_travail",
	"044": "temps_partiel_cotisant_temps_plein",
	"045": "remuneration_pourboire",
	"046": "siret_etablissement_utilisateur",
	"048": "numero_label",
	"049": "numero_licence_entrepreneur_spectacle",
	"050": "numero_objet_spectacle",
	"051": "statut_organisateur_spectacle",
	"052": "fp_code_complement_pcs_es",
	"053": "nature_poste",
	"054": "fp_quotite_travail_temps_complet",
	"055": "taux_temps_travail_partiel",
	"056": "code_categorie_service",
	"057": "fp_indice_brut",
	"058": "fp_indice_majore",
	"059": "fpnbi",
	"060": "fp_indice_brut_origine",
	"061": "fp_indice_brut_cotisation_emploi_superieur",
	"062": "fp_ancien_employeur_public",
	"063": "fp_indice_brut_origine_ancien_salarie_employeur_public",
	"064": "fp_indice_brut_origine_spp",
	"065": "fp_maintien_traitement_origine_contractuel_titulaire",
	"066": "fp_type_detachement",
	"067": "genre_navigation",
	"068": "taux_service_actif",
	"069": "niveau_rx",
	"070": "echelon",
	"071": "coefficient_hierarchique",
	"072": "statut_boeth",
	"073": "complement_dispositif_politique",
	"074": "case_mise_disposition_externe",
	"075": "categorie_classement_finale",
	"076": "contrat_engagement_maritime",
	"077": "college_cnieg",
	"078": "forme_amenagement_temps_partiel",
	"079": "grade",
	"080": "cti",
	"081": "finess_geo",
}
