export interface Etablissement {
	nic?: string,
	apet?: string,
	voie?: string,
	code_postal?: string,
	localite?: string,
	complement_construction?: string,
	complement_voie?: string,
	effectif_fin_periode?: string,
	remuneration_expatries?: string,
	code_pays?: string,
	code_distribution?: string,
	nature_juridique_employeur?: string,
	date_effet?: string,
	date_sortie?: string,
	code_convention_collective?: string,
	opco?: string,
	demande_sortie_dsn?: string,
}
