/**
 * Labels for code_categorie_service (S21.G00.40.056)
 */
export const CATEGORIE_SERVICE_LABELS: Record<string, string> = {
  "01": "[FP] Emploi service sédentaire",
  "02": "[FP] Emploi service actif",
  "03": "[FP] Emploi +800h réseaux souterrains",
  "04": "[FP] Corps identificateurs Préfecture Police Paris",
  "05": "[FP] Emploi 400-529h réseaux souterrains",
  "06": "[FP] Emploi 530-799h réseaux souterrains",
  "07": "[FP] Emploi 400-529h réseaux souterrains ou complément actif",
  "08": "[FP] Emploi 530-799h réseaux souterrains ou complément actif",
  "10": "Fonction Capitaine",
  "11": "Fonction Second capitaine",
  "12": "Fonction Chef mécanicien",
  "13": "Fonction Second mécanicien",
  "14": "Fonction Officier quart passerelle",
  "15": "Fonction Officier quart machine",
  "16": "Fonction Officier électrotechnicien",
  "17": "Marin qualifié Pont",
  "18": "Fonction Matelot équipe de quart",
  "19": "Fonction Matelot sans tâche spécialisée",
  "20": "Marin qualifié Machine",
  "21": "Fonction Mécanicien équipe de quart",
  "22": "Fonction Mécanicien sans tâche spécialisée",
  "23": "Fonction Matelot électrotechnicien",
  "24": "Fonction Opérateur radiocommunications SMDSM",
  "25": "Fonction Cuisinier de navire",
  "26": "Fonction élève machine",
  "27": "Fonction élève pont",
  "28": "Fonction Personnel préparation repas gens de mer",
  "29": "Fonction Personnel d'hôtellerie",
  "30": "Fonction Personnel de propreté",
  "31": "Fonction Personnel de restauration",
  "32": "Fonction Personnel de vente",
  "33": "Fonction Personnel accueil passagers",
  "34": "Fonction Écrivain de bord",
  "35": "Fonction Médecin",
  "36": "Fonction Infirmier",
  "37": "Fonction Hydrographe",
  "38": "Fonction Pilote maritime",
  "39": "Fonction Capitaine Polyvalent",
  "40": "Fonction Second Polyvalent",
  "41": "Fonction Officier Polyvalent",
  "42": "Fonction Marin qualifié Polyvalent",
  "43": "Fonction Matelot Polyvalent",
  "44": "Fonction Commissaire",
  "45": "Fonction Officier électronicien",
  "46": "Fonction élève autre",
  "47": "Fonction élève polyvalent",
  "48": "Fonction Navigant cultures marines",
  "49": "Fonction Personnel usine navire pêche",
  "50": "Travaux actifs 100% [Actifs à 100%]",
  "51": "Travaux mixtes non cadre [Actifs Mixtes non cadre]",
  "52": "Travaux actifs en partie cadre [Actifs Mixtes cadre]",
  "53": "Travaux actifs intermittents non cadre",
  "54": "CSS fonction politique [Actifs à 100%]",
  "55": "CSS fonction politique [Actifs Mixtes non cadre]",
  "56": "CSS fonction politique [Actifs Mixtes cadre]",
  "57": "CSS fonction politique [Actifs Intermittents non cadre]",
  "58": "CSS fonction syndicale [Actifs à 100%]",
  "59": "CSS fonction syndicale [Actifs Mixtes non cadre]",
  "60": "CSS fonction syndicale [Actifs Mixtes cadre]",
  "61": "CSS fonction syndicale [Actifs Intermittents non cadre]",
  "62": "Élu CAS SLV [Actifs à 100%]",
  "63": "Élu CAS SLV [Actifs Mixtes non cadre]",
  "64": "Élu CAS SLV [Actifs Mixtes cadre]",
  "65": "Élu CAS SLV [Actifs Intermittents non cadre]",
  "66": "Sédentaire actif avant A.T. [Actifs à 100%]",
  "67": "Sédentaire actif avant A.T. [Actifs Mixtes non cadre]",
  "68": "Sédentaire actif avant A.T. [Actifs Mixtes cadre]",
  "69": "Sédentaire actif avant A.T. [Actifs Intermittents non cadre]",
  "70": "A disposition CCAS encadrement [Actifs à 100%]",
  "71": "A disposition CCAS encadrement [Actifs Mixtes non cadre]",
  "72": "A disposition CCAS encadrement [Actifs Mixtes cadre]",
  "73": "A disposition CCAS encadrement [Actifs Intermittents non cadre]",
  "74": "Services actifs accord 2010 [Actifs sans Prépondérance]",
  "75": "Sédentaire actif avant A.T. accord 2010 [Actifs à 100%]",
  "76": "Sédentaire actif avant A.T. accord 2010 [Actifs Mixtes non cadre]",
  "77": "Sédentaire actif avant A.T. accord 2010 [Actifs Mixtes cadre]",
  "78": "Sédentaire actif avant A.T. accord 2010 [Actifs Intermittents non cadre]",
  "79": "Sédentaire actif avant A.T. accord 2010 [Actifs sans Prépondérance]",
  "80": "Fonction Lamanage",
  "81": "Fonction Pêcheur à pied",
  "82": "Fonction Autre navigant",
  "83": "Pénibilité P0",
  "84": "Pénibilité P1",
  "85": "Pénibilité P2",
}
