export const CONTRAT_NATURE_LABELS: Record<string, string> = {
  "01": "CDI droit privé",
  "02": "CDD droit privé",
  "03": "Mission (intérim)",
  "07": "CDI intermittent",
  "08": "CDI intérimaire",
  "09": "CDI droit public",
  "10": "CDD droit public",
  "20": "[FP] Détachement avec pension",
  "21": "[FP] Détachement sans pension",
  "29": "Convention de stage",
  "32": "Contrat appui projet entreprise",
  "50": "Nomination fonction publique",
  "51": "COSP ou assimilé",
  "52": "[FP] Cumul activité accessoire",
  "53": "Emploi pénitentiaire",
  "54": "Emploi pénitentiaire apprentissage",
  "60": "Engagement éducatif",
  "70": "Soutien et aide par le travail",
  "80": "Mandat social",
  "81": "Mandat d'élu",
  "82": "CDI chantier/opération",
  "89": "Service civique",
  "90": "Autre",
  "91": "Maritime CDI",
  "92": "Maritime CDD",
  "93": "Ligne de service",
}
